version: '3'

services:
  server:
    build: ./server
    volumes:
      - ./server:/usr/src/app/server
    ports:
      - 4444:4444
    depends_on:
      - db
  db:
    build: ./database
    ports:
      - 5432:5432
    volumes:
      - ./database/pgdata:/var/lib/postgresql/data
  client:
    build: ./client
    volumes:
      - ./client:/usr/src/app/client
    ports:
      - 3000:3000
    depends_on:
      - server
